### PR TITLE
Fix false positive on unused MagicHash extension (fixes #405)

### LINKED ISSUE #405: False positive on MagicHash
Source
```
{-# LANGUAGE MagicHash #-}

module Foo where

foo _ = "_id"#
```

hlint:
```
Foo.hs:1:1: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE MagicHash #-}
Why not remove it.
```

Fixing hint:
```
Foo.hs:4:1: error:
    parse error (possibly incorrect indentation or mismatched brackets)
```

Seems to have been introduced in #358, ping @mitchellwrosen

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks!!!
