### ISSUE TITLE
 hlint doesn't compile with ghc 8.8.1 because haskell-src-exts doesn't and it has no maintainer

### ISSUE THREAD

**Issue by GeorgeCo** [ndmitchell/hlint#755]
hlint doesn't compile with ghc 8.8.1 because haskell-src-exts doesn't and it has no maintainer:

> On Mon, Sep 2, 2019 at 8:48 AM Matthew Pickering <matthewtpickering@gmail.com> wrote:
> I'm not the maintainer of the library anymore. As far as I know it is unmaintained.
> 
> Cheers, Matt
> 
> On Mon, 2 Sep 2019, 12:47 George Colpitts, <george.colpitts@gmail.com> wrote:
> Hi Matthew
> 
> haskell-src-exts doesn't compile with ghc 8.8.1. Any chance that you could fix this soon? 

```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.1

cabal install haskell-src-exts
...
                             [Fixity] -> Exp SrcSpanInfo -> m (Exp SrcSpanInfo)
    • In the first argument of ‘(<=<)’, namely ‘infFix fixs'’
      In the expression: infFix fixs' <=< leafFix fixs'
      In an equation for ‘applyFixities’:
          applyFixities fixs'
            = infFix fixs' <=< leafFix fixs'
            where
                infFix fixs (InfixApp l2 a op2 z)
                  = do e <- infFix fixs a
                       ....
                infFix _ e = return e
   |
72 |   applyFixities fixs' = infFix fixs' <=< leafFix fixs'
   |                         ^^^^^^^^^^^^

src/Language/Haskell/Exts/Fixity.hs:92:25: error:
    • Could not deduce (MonadFail m) arising from a use of ‘infFix’
      from the context: Monad m
        bound by the type signature for:
                   applyFixities :: forall (m :: * -> *).
                                    Monad m =>
                                    [Fixity] -> Pat SrcSpanInfo -> m (Pat SrcSpanInfo)
        at src/Language/Haskell/Exts/Fixity.hs:92:3-15
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            applyFixities :: forall (m :: * -> *).
                             Monad m =>
                             [Fixity] -> Pat SrcSpanInfo -> m (Pat SrcSpanInfo)
    • In the first argument of ‘(<=<)’, namely ‘infFix fixs'’
      In the expression: infFix fixs' <=< leafFixP fixs'
      In an equation for ‘applyFixities’:
          applyFixities fixs'
            = infFix fixs' <=< leafFixP fixs'
            where
                infFix fixs (PInfixApp l2 a op2 z)
                  = do p <- infFix fixs a
                       ....
                infFix _ p = return p
   |
92 |   applyFixities fixs' = infFix fixs' <=< leafFixP fixs'
   |                         ^^^^^^^^^^^^
```

**Comment by ndmitchell** [comment]
Crapola. Someone want to volunteer to fix haskell-src-exts? It's probably not too hard to fix.

**Comment by ndmitchell** [comment]
I have Tweeted out in order to inspire some brave soul: https://twitter.com/ndm_haskell/status/1168635862797737985?s=20

**Comment by vaibhavsagar** [comment]
This has been fixed for months in `head.hackage`: https://gitlab.haskell.org/ghc/head.hackage/blob/master/patches/haskell-src-exts-1.21.0.patch.

**Comment by quasicomputational** [comment]
And a similar PR: haskell-suite/haskell-src-exts#431. The lack really does seem to be a maintainer to merge & cut a new release.

**Comment by DanBurton** [comment]
Regarding haskell-src-exts: I've been given hackage & github privileges, tested & merged [this PR](https://github.com/haskell-suite/haskell-src-exts/pull/431) (nearly identical to the head.hackage patch), and uploaded a new version to hackage: http://hackage.haskell.org/package/haskell-src-exts-1.21.1

**Comment by GeorgeCo** [comment]
Thanks Dan! Works for me, I can now successfully compile hlint which also
seems to work

**Comment by ndmitchell** [comment]
Thanks @DanBurton!
