### ISSUE TITLE
hlint doesn't compile with ghc 9.2.2 

### ISSUE THREAD

**Issue by GeorgeCo** [ndmitchell/hlint#1359]
hlint doesn't compile with ghc 9.2.2 on macos, not sure if it compiles on other platforms

```
 ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.2

 cabal install hlint
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: hlint-3.3.6 (user goal)
[__1] next goal: ghc-lib-parser (dependency of hlint +/-ghc-lib)
[__1] rejecting: ghc-lib-parser-9.2.2.20220307, ghc-lib-parser-9.2.1.20220109,
ghc-lib-parser-9.2.1.20211101, ghc-lib-parser-9.2.1.20211030 (conflict: hlint
+/-ghc-lib => ghc-lib-parser>=9.0 && <9.1)
[__1] trying: ghc-lib-parser-9.0.2.20211226
[__2] next goal: base (dependency of hlint)
[__2] rejecting: base-4.16.1.0/installed-4.16.1.0 (conflict: ghc-lib-parser =>
base>=4.13 && <4.16)
[__2] skipping: base-4.16.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.13 && <4.16' from
'ghc-lib-parser')
[__2] rejecting: base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0,
base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0,
base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
[__2] fail (backjumping, conflict set: base, ghc-lib-parser, hlint)

```

**Comment by GeorgeCo** [comment]
doesn't compile with --allow-new also

```
Building library for hlint-3.3.6..
[ 1 of 60] Compiling EmbedData        ( src/EmbedData.hs, dist/build/EmbedData.o, dist/build/EmbedData.dyn_o )
[ 2 of 60] Compiling Extension        ( src/Extension.hs, dist/build/Extension.o, dist/build/Extension.dyn_o )

src/Extension.hs:64:25: error:
    • Couldn't match type ‘ghc-boot-th-9.2.2:GHC.LanguageExtensions.Type.Extension’
                     with ‘Extension’
      Expected: [(Extension, ([Extension], [Extension]))]
        Actual: [(ghc-boot-th-9.2.2:GHC.LanguageExtensions.Type.Extension,
                  ([ghc-boot-th-9.2.2:GHC.LanguageExtensions.Type.Extension],
                   [ghc-boot-th-9.2.2:GHC.LanguageExtensions.Type.Extension]))]
      NB: ‘Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-lib-parser-9.2.2.20220307’
          ‘ghc-boot-th-9.2.2:GHC.LanguageExtensions.Type.Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-boot-th-9.2.2’
    • In the expression: GhclibParserEx.extensionImplications
      In an equation for ‘extensionImplications’:
          extensionImplications = GhclibParserEx.extensionImplications
   |
64 | extensionImplications = GhclibParserEx.extensionImplications
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hlint-3.3.6 (which is required by exe:hlint from
hlint-3.3.6). See the build log above for details.
```

**Comment by shayne-fletcher** [comment]
thanks for the report. this is to be expected. hlint-3.3.6 does not build with ghc > 9.0.2.

**Comment by GeorgeCo** [comment]
Thanks Shayne. I believe it does compile with ghc 9.2.1 as the bug for that was recently closed.

**Comment by georgefst** [comment]
Isn't this closed by https://github.com/ndmitchell/hlint/pull/1351?

HLint 3.4 is out, with GHC 9.2 support.

**Comment by GeorgeCo** [comment]
yes, this is now fixed
