### ISSUE TITLE
Can't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/hlint#1314]
I can't quite tell if this is a problem with `hlint` itself or maybe the dependencies went out of sync, but I can no longer compile `hlint` with GHC 9.2.1:

```
Building library for hlint-3.3.4..
[ 1 of 59] Compiling EmbedData        ( src/EmbedData.hs, dist/build/EmbedData.o, dist/build/EmbedData.dyn_o )
[ 2 of 59] Compiling Extension        ( src/Extension.hs, dist/build/Extension.o, dist/build/Extension.dyn_o )

src/Extension.hs:64:25: error:
    • Couldn't match type ‘ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension’
                     with ‘Extension’
      Expected: [(Extension, ([Extension], [Extension]))]
        Actual: [(ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension,
                  ([ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension],
                   [ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension]))]
      NB: ‘Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-lib-parser-9.2.1.20211030’
          ‘ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-boot-th-9.2.1’
    • In the expression: GhclibParserEx.extensionImplications
      In an equation for ‘extensionImplications’:
          extensionImplications = GhclibParserEx.extensionImplications
   |
64 | extensionImplications = GhclibParserEx.extensionImplications
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by shayne-fletcher** [comment]
hlint does not currently support building with ghc-9.2.1. work is underway to fix that.

**Comment by garyamorris** [comment]
might be a silly question, new to Haskell. How do I install hlint if I have 9.2.1 installed? cabal install hlint throws errors for me.

**Comment by LeventErkok** [comment]
@garyamorris You can't, until they make a new release. But as I understand it, it should be out any day now.

**Comment by LeventErkok** [comment]
@ndmitchell I just tried to compile HLint 3.3.5, which I thought was going to allow for compilation with GHC 9.2.1; but I'm still getting the exact same compilation error above. Was there something amiss?

**Comment by ndmitchell** [comment]
@LeventErkok - I made a release to allow compiling with aeson-2.0. I've merged a patch that means HEAD should compile with GHC 9.2, but the apply-refact binary (which the CI tests use) won't yet - see https://github.com/mpickering/apply-refact/issues/114. Once that gets fixed I'll do a merge.

**Comment by LeventErkok** [comment]
@ndmitchell @shayne-fletcher 

Looks like the dependence is only for the `apply-refact` part. I do not use hlint to apply the suggestions automatically, and I suspect most end-users like myself does not either.

I'm wondering if you can reduce this dependency by making the "apply" feature conditional, via a cabal-flag. This would allow the mainline users to move on with GHC 9.2.1; and people who want the apply feature can stay with the old version. (Or complain louder!) Or perhaps there's some other trick to avoid this issue?

I understand this is extra work for you, both now and also for future maintenance; but hlint is an important part of the eco-system. Looks like the first commit to https://github.com/ndmitchell/hlint/pull/1247 was on May of last year! almost 8 months ago.

Sorry for being a pest about this; just wondering if the ecosystem can be improved by reducing this dependency to some extent.

**Comment by ndmitchell** [comment]
Do @alanz or @zliu41 have any info on `apply-refact`? Splitting apply into pieces makes it harder for HLint maintainers, and also harder for downstream consumers like Haskell Language Server, so would be an option I'd rather not take. Depends how far away `apply-refact` is.

**Comment by alanz** [comment]
I am down to two failures with GHC 9.2.1, almost there.

**Comment by alanz** [comment]
https://github.com/mpickering/apply-refact/pull/116 should do the trick.

**Comment by LeventErkok** [comment]
@ndmitchell @shayne-fletcher Pinging again! Looks like apply-refact is good to go?

**Comment by ndmitchell** [comment]
@LeventErkok - looks like https://github.com/mpickering/apply-refact/pull/116 is not yet merged. @alanz - is that a pre-requisite? Anything we can do to move that PR forward?

**Comment by LeventErkok** [comment]
@ndmitchell I believe the merge has now gone thru. Right @zliu41 ?

**Comment by zliu41** [comment]
@LeventErkok there are currently two HLint test failures using apply-refact HEAD, and I'm looking into it.

**Comment by zliu41** [comment]
One of the two test failures is fixed in https://github.com/mpickering/apply-refact/pull/120.
I will make a release as soon as I fix the other one.

**Comment by zliu41** [comment]
The other test failure has also been fixed, and I just released apply-refact 0.10.0.0.

**Comment by ndmitchell** [comment]
It's currently failing to compile with:

```
Error:     • Couldn't match type ‘ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension’
                     with ‘Extension’
      Expected: [(Extension, ([Extension], [Extension]))]
        Actual: [(ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension,
                  ([ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension],
                   [ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension]))]
      NB: ‘Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-lib-parser-9.2.2.20220307’
          ‘ghc-boot-th-9.2.1:GHC.LanguageExtensions.Type.Extension’
            is defined in ‘GHC.LanguageExtensions.Type’
                in package ‘ghc-boot-th-9.2.1’
```

@shayne-fletcher - looks like the issue is that HLint is using GHC 9.2.1, and that makes it use ghc-lib-parser-ex 9.2.2, which isn't compatible. Any idea what constraint went wrong here? Do we need to pin more precisely? I think the issue is probably that HLint has the constraint:

> if !flag(ghc-lib) && impl(ghc >= 9.2.2) && impl(ghc < 9.3.0)

While ghc-lib-parser-ex has:

>   if flag(auto) && impl(ghc >= 9.2.0) && impl(ghc < 9.3.0)

And if these aren't perfectly equal everything goes horribly wrong?

**Comment by shayne-fletcher** [comment]
> It's currently failing to compile with:
>...
> And if these aren't perfectly equal everything goes horribly wrong?

https://github.com/ndmitchell/hlint/pull/1353 is getting exercised in CI now. should sort it.
