### PR TITLE
Make it a parse error if you can't parse with ghc-lib-parser.

### PR DESCRIPTION
**Pull request by shayne-fletcher-da**
Pursuant to issue https://github.com/ndmitchell/hlint/issues/645, this PR makes it an error if a `ghc-lib-parser` parse fails.

Test failures are introduced (`Tests failed (3 of 659)`):
(1)
```
SRC: data/hlint.yaml:854:0
INPUT: no = f (#) x
```
(2)
```
SRC: data/hlint.yaml:875:0
INPUT: f rec = rec
```
(3)
```
SRC: data/hlint.yaml:886:0
INPUT: #
```
I have held off on doing anything about them. Please advise on what you'd like to do with these!

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks, I'll go through these errors in a few days.

**Comment by ndmitchell** [comment]
As discussed, the first two are because you don't knock out bad extensions, the last is a wibble in the test suite we can clean up.

**Comment by shayne-fletcher-da** [comment]
I'm going to push again to this branch in a minute but it won't be the last so please hold off on merging - I'll alert you when it's ready to be considered.

File: src/GHC/Util.hs [hunk 1]
```diff
@@ -49,8 +49,25 @@ fakeSettings = Settings
...
+
 enabledExtensions :: [Extension]
-enabledExtensions = [Cpp .. StarIsType] -- First and last extension in ghc-boot-th/GHC/LanguageExtensions/Type.hs 'data Extension'.
+enabledExtensions =
+  -- `Cpp`/`StarIsType` are the first and last extension in
+  -- ghc-boot-th/GHC/LanguageExtensions/Type.hs 'data Extension'. MR
+  -- https://gitlab.haskell.org/ghc/ghc/merge_requests/826 has landed
+  -- which means at some point we can replace with
+  -- `[minBound..maxBound]`.
+  [x | x <- [Cpp .. StarIsType], not (x `elem` badExtensions)]
```
Comment (ndmitchell) [inline src/GHC/Util.hs]: I hope HLint tells you about notElem...

File: src/GHC/Util.hs [hunk 2]
```diff
@@ -49,8 +49,25 @@ fakeSettings = Settings
...
+  , QuasiQuotes
+  , RecursiveDo
+ ]
+
 enabledExtensions :: [Extension]
-enabledExtensions = [Cpp .. StarIsType] -- First and last extension in ghc-boot-th/GHC/LanguageExtensions/Type.hs 'data Extension'.
+enabledExtensions =
+  -- `Cpp`/`StarIsType` are the first and last extension in
+  -- ghc-boot-th/GHC/LanguageExtensions/Type.hs 'data Extension'. MR
+  -- https://gitlab.haskell.org/ghc/ghc/merge_requests/826 has landed
```
Comment (ndmitchell) [inline src/GHC/Util.hs]: This has now landed. Can we switch to minBound/maxBound?

File: src/GHC/Util.hs (hunk 1 above)
Comment (shayne-fletcher-da) [reply src/GHC/Util.hs]: I haven't encountered this nag. Thanks for the hint! Will fix.

File: src/GHC/Util.hs (hunk 2 above)
Comment (shayne-fletcher-da) [reply src/GHC/Util.hs]: I think not because we require `hlint` compile with 8.4 right?

Comment (shayne-fletcher-da) [reply src/GHC/Util.hs]: Argh, of course you are right. I get so confused with this compiler in the compiler :) I'll give it a go.

**Comment by ndmitchell** [comment]
You now have an HLint error in the code with a redundant do.

**Comment by shayne-fletcher-da** [comment]
@ndmitchell With that last commit, we now have ghc flags set from dynamic pragmas. That clears up the errors but introduces new ones. It looks mostly to be about it being an error in GHC to refer to an extension that doesn't exist. These need your review and thoughts about what you'd like to do about them please.
```
TEST FAILURE (1 hints generated)
SRC: src/Hint/Pragma.hs:16:0
INPUT: {-# LANGUAGE A, B, C, A #-}
OUTPUT: src/Hint/Pragma.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE A, B, C, A #-}

  >

WANTED: {-# LANGUAGE A, B, C #-}


(2)
TEST FAILURE (1 hints generated)
SRC: src/Hint/Pragma.hs:17:0
INPUT: {-# LANGUAGE A #-}
OUTPUT: src/Hint/Pragma.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE A #-}

  >

WANTED: <failure>

(3)
TEST FAILURE (1 hints generated)
SRC: src/Hint/Pragma.hs:21:0
INPUT: {-# LANGUAGE A #-}
{-# LANGUAGE B #-}
OUTPUT: src/Hint/Pragma.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE A #-}
    {-# LANGUAGE B #-}
  >

WANTED: <failure>

(4)
TEST FAILURE (1 hints generated)
SRC: src/Hint/Pragma.hs:23:0
INPUT: {-# LANGUAGE A #-}
{-# LANGUAGE B, A #-}
OUTPUT: src/Hint/Pragma.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE A #-}
    {-# LANGUAGE B, A #-}
  >

WANTED: {-# LANGUAGE A, B #-}

(5)
.
TEST FAILURE (1 hints generated)
SRC: src/Hint/Extensions.hs:9:0
INPUT: {-# LANGUAGE TotallyUnknown #-}
f = id
OUTPUT: src/Hint/Extensions.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE TotallyUnknown #-}
    f = id
  >

WANTED: <failure>

(6)
TEST FAILURE (1 hints generated)
SRC: src/Hint/Extensions.hs:11:0
INPUT: {-# LANGUAGE Foo, ParallelListComp, ImplicitParams #-}
f = [(a,c) | a <- b | c <- d]
OUTPUT: src/Hint/Extensions.hs:1:1: Error: Parse error
Found:
    {-# LANGUAGE Foo, ParallelListComp, ImplicitParams #-}
    f = [(a,c) | a <- b | c <- d]
  >

WANTED: {-# LANGUAGE Foo, ParallelListComp #-}
```

File: hlint.cabal [hunk 3]
```diff
@@ -60,7 +60,7 @@ library
         extra >= 1.6.6,
         refact >= 0.3,
         aeson >= 1.1.2.0,
-        ghc-lib-parser >= 0.20190523
+        ghc-lib-parser >= 0.20190603
```
Comment (neil-da) [inline hlint.cabal]: Please make this ==

**Comment by shayne-fletcher-da** [comment]
@ndmitchell This is now ready for review:
- error if ghc parsing fails,
- test suite passes,
- based on 8.8.1

**Comment by shayne-fletcher-da** [comment]
@ndmitchell This is now ready for review if you please:
- error if ghc parsing fails; 
- test suite passes;
- based on 8.8.1.

**Comment by shayne-fletcher-da** [comment]
The last commit was to overcome this error
```
src/Hint/Lambda.hs:152:111: error: parse error on input `='
```
in CI after the unit tests in CI had all passed.
```
src/Hint/Lambda.hs:152:111: Error: Parse error
Found:
        | maybe True (not . isInfixApp) p, (res, refact) <- niceLambdaR [] o
        , not $ isLambda res, not $ any isQuasiQuote $ universe res, not $ "runST" `Set.member` freeVars o
  >     , let name = "Avoid lambda" ++ (if countInfixNames res > countInfixNames o then " using `infix`" else "") =
        [(if isVar res || isCon res then warn else suggest) name o res (refact $ toSS o)]
        where countInfixNames x = length [() | RightSection _ (QVarOp _ (UnQual _ (Ident _ _))) _ <- universe x]
```
I was able to reproduce the failure locally by running the built hlint over that file. I don't understand why parsing that code succeeds when building hlint but fails when parsed with GHC from inside hlint. In any case,  changing the guard to `name <- ...` seems to overcome the issue.

**Comment by ndmitchell** [comment]
The last change needs reverting and figuring out the root cause. Think of HLint as the canary in the coalmine, if something fails on it, you can guarantee it will fail on a bunch of other projects. What's the error? Can you create a smaller example? Most likely its because of an extension, so there may be a harmful GHC extension that we need to disable.

**Comment by ndmitchell** [comment]
I went through everything else and it all looks good, so just that then we can merge.

**Comment by ndmitchell** [comment]
Landed!
