### ISSUE TITLE
Parse error with OverloadedLabels extension

### ISSUE THREAD

**Issue by kiripon** [ndmitchell/hlint#291]
When using `OverloadedLabel` extension, the hlint causes parse error on the label.
The inut is:
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedLabels #-}
import GHC.OverloadedLabels
foo :: (IsLabel "bar" (a -> Int)) => a -> Int
foo x = #bar x
```
And, the result is:
```txt
kiripon% hlint hoge.hs                                                                                                                                                                                                      [howori:~]
hoge.hs:8:9: Error: Parse error: #
Found:
    import GHC.OverloadedLabels
    foo :: (IsLabel "bar" (a -> Int)) => a -> Int
  > foo x = #bar x


1 hint
```

**Comment by ndmitchell** [comment]
Which version of HLint are you using? That works for me with 1.9.37, and finds two suitable warnings.

**Comment by kiripon** [comment]
I have used HLint 1.9.35 (installed via stack lts-7.14).
After I upgraded to 1.9.39, it works fine. There is no error and finds two warning too.
Thank you.
